### ISSUE TITLE
Tiny blocks

### ISSUE THREAD

**Issue by eternaldensity** [NeoSpark314/BeepSaber#14]
I tried the newest release (0.3.1, though I haven't treid 0.3.0 yet) on my Quest 2 and the blocks are very tiny, about the width of the sabers.

**Comment by leandrodreamer** [comment]
that's odd, I've been working with master and it is ok, may be a release build specific bug?

**Comment by NeoSpark314** [comment]
I just tried again with the apk from the release section and do not have this problem (but I only have a Quest 1); can you maybe try to uninstall and reinstall the game?

![image](https://user-images.githubusercontent.com/1610621/115962395-76288880-a51b-11eb-9cfc-0dc34ecc1d07.png)

**Comment by hankedan000** [comment]
For what it's worth, I have seen this bug as well. It was only on a specific song though... I wish I still had the song installed, or could remember what it was.

**Comment by eternaldensity** [comment]
The map it was giving me small cubes on is this one:
https://bsaber.com/songs/7c09/
I'll have to try some other maps and see if there's a pattern to the
problem.  Perhaps it's because it's a 360 map?

**Comment by eternaldensity** [comment]
I tried a different song which was also a 360 map and it did not have tiny blocks.

**Comment by leandrodreamer** [comment]
https://user-images.githubusercontent.com/26260718/118558591-77209480-b72c-11eb-9abe-7fff7751528a.mp4

tried it with that song and indeed it happens, colliders seems to be ok so i suspect that the problem is with the spawn animation no running (since it uses the song speed it may be setting itself at 0), ill take a look to the song file, we could also set a minimum spawn animation speed to prevent this (1 can be minimum since that code it's only intended for very fast songs where u could miss the notes before they end the spawn animation)

**Comment by leandrodreamer** [comment]
yea im pretty sure thats the problem, i think the code uses "_noteJumpMovementSpeed" to set the spawn animation, witch may not be the right value to use since in that song it is 0
regular map:
![imagen](https://user-images.githubusercontent.com/26260718/118559991-6ec95900-b72e-11eb-8216-54b36113e515.png)
this map:
![imagen](https://user-images.githubusercontent.com/26260718/118560042-7f79cf00-b72e-11eb-92c9-72d3f17c20df.png)

it should be pretty easy to fix
edit: on the bsmg wiki it says "_noteJumpMovementSpeed" its the blocks speed, so it is the right value, but i guess maps can set it to 0 (for default maybe), so i guess the fix would be to set a minimun speed to make sure and also ignore that value if is less than 1

**Comment by leandrodreamer** [comment]
https://user-images.githubusercontent.com/26260718/118565235-69244100-b737-11eb-90a9-7d05e1099d29.mp4

added a fix on https://github.com/NeoSpark314/BeepSaber/pull/13 :D

**Comment by eternaldensity** [comment]
aha, that makes sense
